### ISSUE TITLE
Documentation menu not visible on mobile 

### ISSUE THREAD

**Issue by victorlap** [azuyalabs/yasumi#120]
Hey! 

I just wanted to let you know that the menu on the documentation page is invisible on mobile. This makes it impossible to navigate unfortunately.

Great package btw, keep up the good work!

**Comment by stelgenhof** [comment]
@victorlap Thanks for letting me know. I admit I haven't checked it for mobile use. Let me see if I can make it better :)

Cheers! Sacha

**Comment by stelgenhof** [comment]
@victorlap Improvements are coming up! I'm preparing for a new release which include fixes to the documentation as well.

**Comment by victorlap** [comment]
Great!

**Comment by stelgenhof** [comment]
Yasumi v2 has been released. Also the documentation site has been updated so now the menu can be opened on a mobile device as well.
