### ISSUE TITLE
Add holidays

### ISSUE THREAD

**Issue by projct1** [azuyalabs/yasumi#127]
Hio)
How i can add holiday? https://en.wikipedia.org/wiki/Valentine%27s_Day

**Comment by stelgenhof** [comment]
Do you mean you would like to add Valentine's Day to your instance of Yasumi? If so, you can easily use the `valentinesDay` method in the `CommonHolidays` class (Trait).

In case you'd like to add Valentine's Day to an existing holiday provider (e.g. permanently), you can submit a PR for that.

Cheers! Sacha

**Comment by stelgenhof** [comment]
@projct1 Can you let me know if my answer satisfied your question? 
If so, please close this issue or provide more details please.

Cheers! Sacha

**Comment by stelgenhof** [comment]
Closing your issue, assuming your question has been answered. Please feel free to open a new issue if you still have questions.
