### ISSUE TITLE
Provider for Hong Kong

### ISSUE THREAD

**Issue by oallain** [azuyalabs/yasumi#137]
Hello,

I would like to have Hong Kong holidays, does anyone know how to create it?
I do not know how to determine them :(
Thanks in advance.

**Comment by stelgenhof** [comment]
Hong Kong shares similar holidays from China. The challenge with some of the Chinese holidays is that they require some complex algorithm (e.g. Chinese New Year). 

It's possible, but requires some expertise knowledge.

Cheers! Sacha

**Comment by oallain** [comment]
Thanks you for response @stelgenhof :)

I haven't this Knowledge :(

Do you know someone who have it ?

**Comment by stelgenhof** [comment]
I wouldn’t mind investigating and working on this myself, but am pretty busy with some other projects at the moment.

If there is anyone that could help, that would be great.

Cheers! Sacha

**Comment by oallain** [comment]
It would be great, I really need it ;)

Thank you so much !
