### ISSUE TITLE
Provider for Philippines?

### ISSUE THREAD

**Issue by Angelo8828** [azuyalabs/yasumi#142]
Hello Sir @stelgenhof,

I tried to use this package and it's actually great. I'm actually interested to create a provider for Philippines holidays because as of the moment, there's no open-source projects written yet for providing data for Philippine holidays in PHP. Will it be alright if I will try to contribute something to the project?

Cheers and regards,

**Comment by stelgenhof** [comment]
Hi @Angelo8828,

Thank you for willing to contribute to this library. New countries are more than welcome! The best way to get started is by looking at other country providers (you can even copy one as a begin).

Let me know if you have any questions.

Cheers! Sacha
