### ISSUE TITLE
Provider for Mexico

### ISSUE THREAD

**Issue by gogl92** [azuyalabs/yasumi#143]
Creating the provider for Mexico is not too difficult except for the holidays that are adjusted to the closest monday.

**Comment by stelgenhof** [comment]
Thanks! Is this issue just a request or are you planning on contributing the provider for Mexico?

Having holidays that are observed to the next Monday in case a national holiday is not difficult. You can see the code of other holiday providers how it is done.

Cheers! Sacha

**Comment by gogl92** [comment]
I will try to make the contribution and create the pull request.

**Comment by stelgenhof** [comment]
@gogl92 Cool! Let me know if you have any questions. Best is to use one of the existing countries as a starting point. FIY, your PR needs to be made against the develop branch :)

Cheers! Sacha

**Comment by stelgenhof** [comment]
@gogl92 Wanted to check if you have made any progress with the Mexico provider. If not and you don’t have any time, I can take it over if you like
