### ISSUE TITLE
Symfony 4 integration

### ISSUE THREAD

**Issue by TELLO0815** [azuyalabs/yasumi#144]
Hi all,

sorry im new bee.
I want to use Yasumi to check in Symfony the date for Swiss if it is a holiday or not. How can I get datas for two years? Like im on the end of the year... Or must I write it with the year now and second array with the year + 1? 

```
$holidays_1 = Yasumi\Yasumi::create('USA', 2019);
$holidays_2 = Yasumi\Yasumi::create('USA', 2020);
```

TELLO

**Comment by stelgenhof** [comment]
Hi,

At the moment there is only one way of doing it and that is like in your example: you would need to instantiate Yasumi twice. This is because the Yasumi class only can cover a single year.

Cheers! Sacha

**Comment by stelgenhof** [comment]
@TELLO0815 Just want to get back to you. Did my reply answer your question? If so, I will close this issue.
