### ISSUE TITLE
[France] Wrong OfficialHolidays

### ISSUE THREAD

**Issue by R2c** [azuyalabs/yasumi#17]
I have some troubles with France official holidays
The GoodFriday (25-03-2016) and  stStephensDay (26-12-2016) aren't official holidays
It's true for "Alsace-Moselle" but not for all France

Nice idea this lib :+1:

**Comment by stelgenhof** [comment]
Thanks for the feedback. Let me have a look. It has been a while when France was added :)

**Comment by stelgenhof** [comment]
Just checked and you are right. In case a country has regional holidays I implement separate regional holiday providers. Since that takes a bit more time, I will remove these two holidays then from France. Later will add a separate holiday provider for Alsace and Moselle.

**Comment by stelgenhof** [comment]
@R2c Looking on the page https://fr.wikipedia.org/wiki/F%C3%AAtes_et_jours_f%C3%A9ri%C3%A9s_en_France#Tableau_r.C3.A9capitulatif I don't see Alsace, but do see Moselle mentioned. In France are some holidays observed by département or rather region?

**Comment by R2c** [comment]
**In France are some holidays observed by département or rather region?**
No, but we have just one expection for 3 départements "Moselle, du Bas-Rhin, du Haut-Rhin". 
Bas-Rhin, du Haut-Rhin == Alsace

**"I will remove these two holidays then from France. Later will add a separate holiday provider for Alsace and Moselle."**   
:+1: :+1:

**Comment by stelgenhof** [comment]
Thanks! Let me then add separate holiday providers by département (similar to the Spain implementation).

**Comment by stelgenhof** [comment]
Fixed issue for France as Good Friday and St. Stephens Day were defined as official holidays. These aren't national holidays and are only observed in the French departments Moselle, Bas-Rhin and Haut-Rhin. With this fix, these holidays have been removed from the France Holiday providers and new providers for the departments Moselle, Bas-Rhin and Haut-Rhin are added.
