### ISSUE TITLE
language agnostic holiday definitions

### ISSUE THREAD

**Issue by huehnerhose** [azuyalabs/yasumi#179]
I really love yasumi :) It works like a charm and is very well maintained. 

At the moment I need something just like yasumi, but for golang. It seems like there is nothing of this sort. Which led me to the idea of sharing the data-basis of yasumi more generic and make it possible to implement the logic around the data-basis in any language needed. 

To do this, we would need some kind of "holiday description language". I do not know all corner cases currently existing in yasumi. So do you think it is possible to create such a language or is it a lost cause?

**Comment by stelgenhof** [comment]
Thank you for the kind words :) I am doing my best to make Yasumi as user/developer friendly as possible.

As for your question, are you merely interested in the holiday data or actually the holiday logic? If it is the logic you are looking for, then I don't know any common language that could describe this. 

Holidays are in many cases pretty regular in terms of their pattern, but there are numerous exceptions and undocumented governmental changes. Not sure how this could be adequately captured with some kind of language. Or we need to create one :)
