### ISSUE TITLE
How to add yasumi to laravel?

### ISSUE THREAD

**Issue by tuanntjvb** [azuyalabs/yasumi#187]

**Comment by stelgenhof** [comment]
The Yasumi  class is a simple factory class that you can use anywhere in your Laravel application, e.g. the controllers, models, or other classes.

Another possibility is to register it in your Service Provider class so it is available everywhere in your application.

**Comment by stelgenhof** [comment]
In case you're looking for a Laravel package, there is one created by somebody in the community: https://github.com/blood72/laravel-yasumi. Although I haven't used it myself, it may be what you're looking for.

Cheers! Sacha
