### ISSUE TITLE
RFC: Using class constants for holiday names

### ISSUE THREAD

**Issue by ravage84** [azuyalabs/yasumi#198]
This is a Request For Comment.

To be honest, I just came across your fine library,haven't had a chance to use it yet.
But while I was browsing through the documentation and code, I was wondering **why the names of the holidays are (magic) literals instead of class constants**.

So ,for example, instead of doing this:

````php 
        $this->removeHoliday('christmasDay');
        $this->removeHoliday('secondChristmasDay');
        $this->removeHoliday('someOtherSwissNationalHoliday');
````

It could be this:

````php 
        $this->removeHoliday(Holidays::CHRISTMAS_DAY);
        $this->removeHoliday(Holidays::SECOND_CHRISTMAS_DAY);
        $this->removeHoliday(SwissHolidays::SOME_OTHER_HOLIDAY);
````

Magic literals _can_ become a maintenance problem. Having class contants for them would centralize those magic literals, contain them & would make it possible to document them (with doc blocks, for example). Also having them would improve the developer experience as it would make them searchable through the IDEs.

**Comment by stelgenhof** [comment]
As for the why, there isn't a particular reason and definitely agree that class constants should be used instead. It might take a bit of time before all literals are transposed to class constants.

Cheers! Sacha
