### ISSUE TITLE
Date addition (Australia Day Subdivision: AU-SA / Year: 2020)

### ISSUE THREAD

**Issue by jbroudou** [azuyalabs/yasumi#199]
It appears from https://www.safework.sa.gov.au/law-compliance/laws-regulations/public-holidays that in 2020 in South Australia, 2020-01-26 (Sunday) and 2020-01-27 (Monday) are both "Australia Day" public holidays. See specifically footnote 1 on this website which states: "If a Saturday, normal rates apply and the following Monday is the public holiday. If a Sunday, that and the following Monday are both public holidays."

Your project is currently only recording 2020-01-27 (Monday) as Australia Day.

It would be great if you could add the additional Sunday.

**Comment by stelgenhof** [comment]
Thanks for spotting this one. Although in the code a substitution is performed, it actually overwrites the original holiday resulting the original one not to be present. The code for Australia needs a bit of rework as it doesn't apply the **SubstituteHoliday** class that recently was introduced.
