### ISSUE TITLE
A Naming Convention Issue on Australian States

### ISSUE THREAD

**Issue by hugowebtools** [azuyalabs/yasumi#210]
I was trying to create two objects for Victoria and New South Wales in Australia and I realised the the holiday providers for these two states were using different naming conventions.

```
$provider = Yasumi::create('Australia/NSW', 2020);
$provider = Yasumi::create('Australia/Victoria', 2020);
```

If we check the list of providers, we can easily see there are 5 states in Australia using their abbreviations as the class name against the others. 
![Screen Shot 2020-03-12 at 16 04 08](https://user-images.githubusercontent.com/50603301/76488969-315aa300-647b-11ea-9ce5-8e067ce0c765.png)
I don't think it is correct. Based on the naming conventions used for states in Germany, maybe we can simply align Australia states to reduce confusion. 
```
   NSW  =>  NewSouthWales
   ACT  =>  AustralianCapitalTerritory
   WA => WesternAustralia
   SA => SouthAustralia
   NT => NorthernTerritory
```

**Comment by Milamber33** [comment]
As the guy who actually built all of the Australian providers, my apologies. :)
Personally, I'm using Yasumi::createByISO3166_2 rather than just Yasumi::create, so if someone feels like changing this I am not opposed.

**Comment by hugowebtools** [comment]
Ah, it is. I can see `Yasumi::createByISO3166_2` a cool feature and it is very useful. I must miss it in the documentation. Thank you.

**Comment by stelgenhof** [comment]
To have consistency, renaming them would be good indeed. I can make that change if you like, other otherwise feel free to submit a PR :)

Cheers! Sacha
