### ISSUE TITLE
Feature/Add Holidays for Mauritius Island and Other African Countries

### ISSUE THREAD

**Issue by theArtechnology** [azuyalabs/yasumi#229]
I would be glad if you could add holidays to my country (Mauritius) and other African countries :
The official list from [SADC](https://www.sadc.int/) :

https://www.qppstudio.net/publicholidays2020/sadc.htm

**Comment by stelgenhof** [comment]
@theArtechnology Thank you for the PR! Definitely Mauritius can be added, as there aren't yet many African countries supported (except South Africa).

**Comment by theArtechnology** [comment]
@thedreamatorium
