### ISSUE TITLE
prevWorkingDay/nextWorkingDay to take into account only official holidays

### ISSUE THREAD

**Issue by tadasauciunas** [azuyalabs/yasumi#232]
Hi, I have a feature request for `prevWorkingDay` / `nextWorkingDay` methods. I want the ability to ask the `isWorkingDay` method to return true only on official holidays. Currently it returns true on observance and other types of holidays, and that makes the `prevWorkingDay` / `nextWorkingDay` functions not work correctly in our case, since observance holidays might be working days officially. 
I'd be happy to put in a pull request with an optional query parameter to the mentioned methods that does not change the current behavior unless you set it explicitly, to keep compatibility. Let me know if you think this sort of functionality would be useful.

**Comment by tadasauciunas** [comment]
My bad, apparently not all 'observance' holidays should be removed from the list we need, so extending the holiday providers and removing the unnecessary holidays will be enough in our case.

**Comment by stelgenhof** [comment]
Hi @tadasauciunas Extending the providers is definitely a solution. However I am aware that the way Yasumi determines a working day / non working day is not working correctly. Working on that one... :)
