### ISSUE TITLE
Spain and Catalonia: Valentine's day is not holiday

### ISSUE THREAD

**Issue by jroman14** [azuyalabs/yasumi#234]
Hi mate,
valentin day is not holiday in spain and catalonia. Can you update that?

Thanks for your job

**Comment by sachatelgenhof** [comment]
Hi, Valentine's Day is indeed in most countries not an official holiday. For Spain it is classified as 'OTHER' meaning not an official holiday. Do you have a particular issue when using Yasumi for Spain?

**Comment by jroman14** [comment]
Hi I'm using getHolidayDates function to save in internal calendar. Then valentines days appear as holiday. There are any method to filter days classified as Other?
Thank you again!

**Comment by stelgenhof** [comment]
Yes, you can use filters for that. Have a look at the documentation here: https://www.yasumi.dev/docs/cookbook/filters/
The **OfficialHolidays** filter will exactly do what you need.

Cheers! Sacha
