### ISSUE TITLE
Adding other USA holidays

### ISSUE THREAD

**Issue by shoutbomb** [azuyalabs/yasumi#243]
Wondering if these are planned for a future release;

Lincoln's Birthday
Yom Kippur
Rosh Hashanah
Day after Thanksgiving
Pioneer Day... July 24th annually for Pioneer Day which is a state holiday in Utah

Many Thanks for this project,
George

**Comment by stelgenhof** [comment]
Hi @shoutbomb ! Not directly planned, but these can definitely be added of course.
And a big thank you for the 'coffee'! That is quite a lot :)

**Comment by shoutbomb** [comment]
No problem your work has made my work easier.

**Comment by shoutbomb** [comment]
Hello Sacha,

Do you consider 'sponsorship' for enhancement requests or is it FIFO?  If you do, I would like to discuss this further.

Thanks....

**Comment by stelgenhof** [comment]
Hi @shoutbomb Yes can consider that. You can contact me directly to discuss further if you like.
