### ISSUE TITLE
Use country code instead of name?

### ISSUE THREAD

**Issue by websecureNL** [azuyalabs/yasumi#244]
I could not find this in the documentation, but is it possible to create a new holiday provider instance with the country code instead of name?

So 
Yasumi\Yasumi::create('NL', $year); 
instead of 
Yasumi\Yasumi::create('Netherlands', $year);

**Comment by stelgenhof** [comment]
Yes, there isn't really an extensive API documentation. To answer your question, you can already do that using an alternative method: `createByISO3166_2` :)

**Comment by websecureNL** [comment]
Great! Thank you for your work and the quick reply :-)
