### ISSUE TITLE
PHP / solution HELP

### ISSUE THREAD

**Issue by pete1019** [azuyalabs/yasumi#247]
Hi @stelgenhof,

again: thanks a lot for your great work.
need your help on PHP code please. I am not good at all but would love to see your solution. As much detail as possible so i understand.

- holidays Netherlands
- remove kingsDay
- remove liberationDay
- check the current date when .php is opened
- if today is a holiday print the name like christmasDay
- if it is not a holiday print noHoliday

THANKS A LOT!

**Comment by stelgenhof** [comment]
Hi @pete1019 
Sure! For starters to remove holidays from an existing provider, you can use a custom filter. Or more advanced you could create your own custom provider based on an existing one:  https://www.yasumi.dev/docs/cookbook/custom_provider/

For the current date, you can use the standard PHP date functions for that: https://www.php.net/manual/en/function.date.php

You can use the `isHoliday` method to check if the current day is a holiday or not.

Hope this helps!

**Comment by pete1019** [comment]
@stelgenhof 

Thanks. Thought you might be able to post some code here for me to use right away.

To strip it down a little bit this might be enough for now:
Print the name like "christmasDay" of the current day.

Again: Thanks  lot!

**Comment by stelgenhof** [comment]
@pete1019 Good! A few tips/pointers:
- You can use the `date_default_timezone_get` PHP function to retrieve the default timezone. Not necessary to execute a command via the shell
- To avoid parsing the country name / provider name, you can alternatively use the `createByISO3166_2` function which takes the ISO3166 2 character code of a country (e.g. 'NL', 'DE')
- Not necessary to use `strval` (typecasting), as the variables used are already strings. Better is to compare the actual DateTime variables.
- The second argument of the `create`and  `createByISO3166_2` functions take an integer type variable. The `date` function returns a string. You may want to do a type cast here.
- Assuming the `die` functions are for testing purposes. Better to use `exit` or handle the conditions accordingly.

**Comment by stelgenhof** [comment]
Closing, as I assume your question has been answered :)

**Comment by pete1019** [comment]
@stelgenhof yes thanks again!
