### ISSUE TITLE
Holidays for Turkey?

### ISSUE THREAD

**Issue by AliMoonICT** [azuyalabs/yasumi#248]
Would you please add holidays for Turkey? 

For Turkish : https://www.takvim.com/2021_takvimi.html 
For English : https://www.officeholidays.com/countries/turkey/2021

Thanks in advance.

**Comment by stelgenhof** [comment]
@AliMoonICT Started working on it: You can check the `turkey` branch (WIP).

**Comment by ChrisTitos** [comment]
Hey, any idea when version 2.5 will be released? We also need Turkey. (for now I just copied the class into my code so I at least have something)
Thanks.

**Comment by stelgenhof** [comment]
@ChrisTitos Working on the documentation at the moment. Hopefully release will be done by the end of next week.
