### ISSUE TITLE
"Fronleichnam" missing as official Holiday

### ISSUE THREAD

**Issue by pete1019** [azuyalabs/yasumi#252]
Hi,

"Fronleichnam" is missing as official holiday today. Why is that?
Not listed in NRW nor Bayern. Don't know if others are missing, too.

Thanks a lot

**Comment by stelgenhof** [comment]
Hi, Could you share some sample code that shows the holiday is missing? Thanks!

**Comment by pete1019** [comment]
Sure:

`
require_once 'vendor/autoload.php';


if (isset($_GET['c']) && isset($_GET['t'])) {


    $tz = $_GET['t'];

    if ($tz === 'Default Timezone') {
        $tz = `date +%:z`;
    }

    $dt = new \DateTime('now', new \DateTimeZone($tz));
    $c = str_replace('-', "\\", $_GET['c']);
    $c = str_replace('-', "//", $c);
    $c = str_replace('-', "/", $c);
    // $is_holiday = Yasumi\Yasumi::create($c, date('Y'))->isHoliday($dt);

    $d = $dt->format('Y-m-d');
    $ho = Yasumi\Yasumi::create($c, date('Y'));
    $**official** = new Yasumi\Filters\OfficialHolidaysFilter($ho->getIterator());
    foreach ($official as $h) {
        if (strval($d) === strval($h))
            die('isholiday');
    }
    die("notholiday");
}
`

Thanks!

**Comment by stelgenhof** [comment]
Thanks for the example. I just found out that Corpus Christi is by default set to 'Other' which is likely the most sensible classification for any country that celebrates it. This is the case for Germany (and it's states) as well. Hence why these don't show up.

A reclassification for the respected states is then necessary in Yasumi.

**Comment by pete1019** [comment]
Thanks. When might a fix be available?

**Comment by pete1019** [comment]
Hi, any news on this? Thanks a lot

**Comment by stelgenhof** [comment]
I will look into it this week. Thanks for the reminder!

**Comment by stelgenhof** [comment]
@pete1019 I have created a PR that will fix this issue. If you like to verify, please have a look at this PR.

**Comment by pete1019** [comment]
Thanks, how can i download and check?

**Comment by stelgenhof** [comment]
You can checkout the `fronleichnam-fix` branch.

**Comment by pete1019** [comment]
ahh you mean this:
https://github.com/azuyalabs/yasumi/tree/fronleichnam-fix

okay i will test it and let you know.

**Comment by pete1019** [comment]
i tried downloading the code.zip and tried to replace the src folder but i got and internal server error.
I had it working with composer.
How to get the fix "composer-friendly"?

Thanks

**Comment by stelgenhof** [comment]
@pete1019 I don't think that would work indeed. If you want to go the Composer route, you would need to change the Yasumi version in your `composer.json` with the desired branch (see: https://getcomposer.org/doc/articles/aliases.md#why-aliases-)

You can also checkout the branch with Git and have your script point to that.

**Comment by pete1019** [comment]
@stelgenhof thanks and how will i deal with this on 2.4.0?
- _Removed PHP 7.2 Support (PHP 7.2 is EOL)_

I can not upgrade PHP 7.2 at this point.

Is your fix only available for 2.4.0 which does not have PHP 7.2 support anymore?
https://github.com/azuyalabs/yasumi/tree/fronleichnam-fix

THANKS!

**Comment by stelgenhof** [comment]
@pete1019 It will be fixed in the upcoming 2.5.0 release. 2.4 and 2.5 have support for PHP7.3 or higher as these are the official supported PHP versions.

**Comment by pete1019** [comment]
@stelgenhof so i am out of luck with PHP 7.2 for now? I need to upgrade to 7.3?
You used special PHP 7.3 functions or is it just coded that PHP 7.2 is not allowed to use with YASUMI anymore?
Thanks.

**Comment by stelgenhof** [comment]
@pete1019 Don't know by heart but probably some specific 7.3 syntax indeed is used since 2.4.

**Comment by stelgenhof** [comment]
@pete1019 Were you able to do some checks?

**Comment by pete1019** [comment]
@stelgenhof unfortunately not since the PBX i am using it on still is on PHP 7.2. Hope at least PHP 7.3 in the next weeks / months.

**Comment by stelgenhof** [comment]
@pete1019 I went ahead and merging your PR. I am aware you may not have time yet to check everything, however if we find some issues we can always fix them at any time.
