### ISSUE TITLE
Mistyping in SouthKorea Provider

### ISSUE THREAD

**Issue by barami** [azuyalabs/yasumi#254]
Hi.

In SouthKorea provider ```src/Yasumi/Provider/SouthKorea.php```, LUNAR_HOLIDAY constant has mapping table for 'seollal' and it has entry for year 2039, but date value is year 2037.

We should change ```2039-1-24``` instead of ```2037-1-24```.

Thanks.

**Comment by stelgenhof** [comment]
@barami Thank you very much for spotting this! I will make a correction.

**Comment by stelgenhof** [comment]
Fixed in the `dev` branch (Targeted for the 2.5 release).
