### ISSUE TITLE
[Doc / Help] How can we exclude 25 and 26 of december from holidays?

### ISSUE THREAD

**Issue by realtebo** [azuyalabs/yasumi#265]
> Yes.. absurd request. I hate my customer ... 

I am using your excellent package to exclude holidays when users do orders on a store and choose delivery date.

This year we _must allow_ 25 and 26 december, so we need to filter out these days when checking 

                    $holidays_in_this_day = $holidays->between(
                        $slot_period->toDate(),
                        $slot_period->toDate()
                    );

We would like to DO NOT consider as holidays these 2 days.

How?

**Comment by realtebo** [comment]
I created a custom provider extending Italy

And did this

    /**
     * Initialize holidays for the NYSE.
     * @throws  \Exception
     */
    public function initialize(): void
    {
        parent::initialize();

        // Remove Columbus Day and Veterans Day
        $this->removeHoliday('christmasDay');
        $this->removeHoliday('stStephensDay');
    }


But this year `stStephensDay` is a Sunday, so I must remove THIS specific sunday.

How ?

**Comment by stelgenhof** [comment]
@realtebo Thank you for your question! Creating a custom provider is a good option indeed. Alternatively, you can also try  creating your own filter where your filter out the unwanted holidays. (https://www.yasumi.dev/docs/cookbook/filters/).

If you use `$this->removeHoliday('stStephensDay')` does it not do what you need? Looks to me your provider is exactly removing the 25th and the 26th. Or do you get some unexpected results?
