### ISSUE TITLE
Mothering Sunday in the UK

### ISSUE THREAD

**Issue by kennydude** [azuyalabs/yasumi#266]
Mothers Day or, the british term, Mothering Sunday is on a different day to the default - https://en.wikipedia.org/wiki/Mothering_Sunday

It would be great if this could be added

**Comment by stelgenhof** [comment]
Hi @kennydude I've added Mothering Sunday for the United Kingdom. You can check/verify the changes in this branch: https://github.com/azuyalabs/yasumi/tree/feature/mothering-sunday

I am targeting this to include it in release 2.5.0 which I plan to release next week. Let me know if something is incorrect or missing.

Cheers!

**Comment by stelgenhof** [comment]
Feature completed. Work merged into the `develop` branch.

**Comment by Jimbob001** [comment]
@stelgenhof Hi there, was about to write a separate issue when I saw this.

Mothering Sunday isn't classed as a "public holiday", albeit it being a null point given it's always on a Sunday! However, it looks odd appear in the standard holiday list with bank holidays etc.

I know better classification is in the works, to split out these sorts of days, but I wonder whether it's worth having in the standard list until then?

It also doesn't appear in the source cited in your documentation, if that's another factor: https://en.wikipedia.org/wiki/Public_holidays_in_the_United_Kingdom

**Comment by Jimbob001** [comment]
@stelgenhof thank you for the response. I was using the standard unfiltered list. Setting to official holidays only gives me two results!

What I've done is manually filtered out the "other" type to remove this and potentially other additions. This matches up with what most people would expect in terms of whether this day counts towards holiday entitlement (which is my use case in a nutshell).

Many thanks for the help :)

**Comment by stelgenhof** [comment]
@Jimbob001 I checked myself and indeed it only results in two holidays. This is due the nature of the Filter classes in that they exclusive filter for that particular category. 

For your use case, these filters may not give the results you need. Manually filtering out the 'other' holidays is then certainly a solution :) Or you could create your own filter doing all of that.

Cheers! Sacha
