### ISSUE TITLE
Christmas day in Spain

### ISSUE THREAD

**Issue by sylvaincombes** [azuyalabs/yasumi#267]
In Spain, when christmas is on a sunday (as it will be in 2022), the holiday will be on the monday 26/12, I will propose a PR to update this behaviour.

**Comment by stelgenhof** [comment]
@sylvaincombes Is this because of a recent change in regulations or has this been incorrect in Yasumi all the time?

**Comment by sylvaincombes** [comment]
After thinking a little more about it :

- It has been said to me by a native one as a general rule
- But searching online I didn't find precise clear confirmation of that rule
- I think maybe we should handle it better like some case where I saw keys like "substituteHoliday:christmasDay" and let Christmas on 25/12
- If we can have some help by spain natives it would be great
