### ISSUE TITLE
Some stats methods in AbstractProvider 

### ISSUE THREAD

**Issue by zhikiri** [azuyalabs/yasumi#27]
Hi
I want to propose some additional methods for the AbstractProvider class.
Can be useful to have something like: `countWorkHours()` and `countHolidayHours() `.

I can make it, just want to know, what do you think about it ?

**Comment by stelgenhof** [comment]
Hi @zhikiri 
That sounds a good idea, although I don't yet understand how to use that. Could you give a real life example what these methods would provide? Also keep in mind this library is primarily intended for days (not specific hours).

**Comment by zhikiri** [comment]
Hi @stelgenhof 
Yes, no problem, I'll give some example. 
On some site I want to display some stats about people lazy :) and I want to group this data by country. 
If I can use `yasumi` for get this information and it will be perfect.
About last sentence, I understood your point ;)

**Comment by stelgenhof** [comment]
I see what you are looking for. I am not sure Yasumi is the right library for your purpose. My first question is how do you define the work hours? This can be different per country/company/... What you can use Yasumi for is the determine the holidays. Then again you need to make some kind of assumption what the actual hours are. As said tracking hours is unfortunately not the main purpose of Yasumi.

**Comment by zhikiri** [comment]
Ou, ok. 
Thanks for you time.
