### ISSUE TITLE
pentecost Monday France

### ISSUE THREAD

**Issue by kl3sk** [azuyalabs/yasumi#281]
Hello,

As I know since [2004](https://fr.wikipedia.org/wiki/Journ%C3%A9e_de_solidarit%C3%A9_envers_les_personnes_%C3%A2g%C3%A9es_et_handicap%C3%A9es) this not a holiday anymore.

This day should not be count as one or may be optional.

**Comment by stelgenhof** [comment]
Hi @kl3sk Thank you very much for noting this. I will make a correction accordingly.

**Comment by stelgenhof** [comment]
Hi @kl3sk I've made a fix for this, which you can find in this branch: https://github.com/azuyalabs/yasumi/tree/pentecost-monday-france.

**Comment by stelgenhof** [comment]
Hi @kl3sk Can you let me know if the fix I made addresses your issue? Thanks!

**Comment by stelgenhof** [comment]
Fixes merged to the `develop` branch.

**Comment by kl3sk** [comment]
Hello @stelgenhof,

Thank you for the update.

I did yet found time to test. I'll come back when I can test it on my project.

**Comment by kl3sk** [comment]
Hello @stelgenhof  sorry for the late time.

I tried with `@dev-develop` and found that `return false` for `$yasumi->isHoliday(new \DateTime('2022-06-05'))` that is the intended behaviour.

But ! It look likes `@master` (eg: `v2.5.0`) returns the same.
