### ISSUE TITLE
Unable to find holiday provider "Cyprus"

### ISSUE THREAD

**Issue by bkintanar** [azuyalabs/yasumi#284]
Missing holiday for Cyprus. Here are the list https://www.officeholidays.com/countries/cyprus/2022

**Comment by stelgenhof** [comment]
Thank you very much for your question and PR to add Cyprus to the list! Very much appreciated.

**Comment by bkintanar** [comment]
No worries. I will add more test cases maybe later but wanted you to take a look into the PR since it's my first PR and I wanted to see if I'm doing it correctly.
