### ISSUE TITLE
Japanese 2020 Marine Day(海の日）

### ISSUE THREAD

**Issue by mocchii2** [azuyalabs/yasumi#290]
In the Japanese calendar for 2020, Marine Day is currently set to July 20, but this year the Olympics were scheduled to be held, so the date was changed, and July 23 is the correct date for this year only.

**Comment by stelgenhof** [comment]
Thank you for this. I will have a look. If you like to create a PR for this  that would even greater :)

**Comment by stelgenhof** [comment]
Fixed in `develop` branch.
