### ISSUE TITLE
False holiday in Germany 31.12.

### ISSUE THREAD

**Issue by vedagel** [azuyalabs/yasumi#294]
Dear contributors,

thank you very much for the very nice project!

We noticed that 31.12.YYYY is classified as a holiday in Germany, although it is actually not. How can this be fixed?

Thanks

**Comment by stelgenhof** [comment]
Hi @vedagel Thank you for your question. New Years Eve (12/31) is for Germany classified as "OTHER", meaning it is a defined day in Yasumi but not considered 'Official'. See https://github.com/azuyalabs/yasumi/blob/3214f01bf6bad7a70ce4a39c0a7b2331fb88fd2c/src/Yasumi/Provider/Germany.php#L51

Do you mean it should be a different classification then?

**Comment by vedagel** [comment]
> Do you mean it should be a different classification then?


Hello, thank you for your reply. As you can see at https://en.wikipedia.org/wiki/Public_holidays_in_Germany, December 31 is never a holiday, so I think it is also not an "other" holiday.

**Comment by stelgenhof** [comment]
Yes, the concept of 'holiday' in Yasumi is perhaps not the same as the usual public holiday. In Yasumi a holiday is any day that is considered of some significant, cultural, historical event (which includes also the usual common public holidays). For those days in Yasumi that are not official public holidays, they can still be registered and classified as 'Other'.

**Comment by reinfi** [comment]
Hey, i stumpled upon this problem while using this great library. 

Would there be an option to add a method for selection official holidays in an easy way?
My problem is that either `isWorkingDay` nor `isHoliday` let me exclude the "other" holidays. 

For that reason I need to write ugly code like:

`
$holidaysOnDate = $this->holidayProvider->on($date);
$holidaysOnDate->rewind();

$holidayOnDate = $holidaysOnDate->current();

if (!$holidayOnDate instanceof Holiday) {
  return false;
}

return $holidayOnDate->getType() === Holiday::TYPE_OFFICIAL;
`

Any suggestions on this? Easiest solution would be to provide some sort of Parameter to the `isWorkingDay` or add another method.

**Comment by stelgenhof** [comment]
@reinfi You can certainly do this using the included filters. See the documentation here: https://www.yasumi.dev/docs/cookbook/filters/ 

In short, you only would need to do the following: `$official = new Yasumi\Filters\OfficialHolidaysFilter($holidays->getIterator());`

**Comment by reinfi** [comment]
I found this before but this does not help me to achieve a short and easy way to check a date if it is an official holiday. 

I decided to remove the holiday after creating it, cause new holidays are rarely common :-) 

```
$this->holidayProvider = new Germany\NorthRhineWestphalia($date->year);

$this->holidayProvider->removeHoliday('newYearsEve');
```

**Comment by stelgenhof** [comment]
@reinfi Not sure about your specific use case, but using filters would be the best approach as these can also be easily (unit) tested. Of course, removing the holiday, like you did, works as well.
