### ISSUE TITLE
German holiday epiphany should be an official holiday

### ISSUE THREAD

**Issue by AnnaDamm** [azuyalabs/yasumi#296]
The Holiday on the 6th of January should be an official holiday in Baden-Württemberg, Bavaria and SaxonyAnhalt.

Currently, it is marked as type "other" instead of "official"

**Comment by stelgenhof** [comment]
@AnnaDamm Do you perhaps have a source for this? Is this a (recent) change or was it just incorrectly classified in Yasumi from the start?

**Comment by AnnaDamm** [comment]
Bavarian Law (at least from 1980, not sure about before): https://www.gesetze-bayern.de/Content/Document/BayFTG-1
Sachsen Anhalt Law (at least from 2004): https://www.landesrecht.sachsen-anhalt.de/bsst/document/jlr-FeiertGSTrahmen
