### ISSUE TITLE
Missing holiday in Augsburg/Bavaria/Germany

### ISSUE THREAD

**Issue by AndiLeni** [azuyalabs/yasumi#304]
Hello,

the city Augsburg has a unique holiday on 8th August each year, which is not celebrated in the rest of bavaria or germany.

https://en.wikipedia.org/wiki/Public_holidays_in_Germany
https://de.wikipedia.org/wiki/Augsburger_Hohes_Friedensfest
https://www.augsburg.de/kultur/festivals/hohes-friedensfest

**Comment by stelgenhof** [comment]
Hi @AndiLeni Thank you very much for this issue. Yasumi only is designed to record holidays for countries and subdivisions (such as states, provinces, etc.) but not cities. We can add this holiday to Bavaria, but it would mean Yasumi considers it a holiday for the entire Bavaria region.

**Comment by AndiLeni** [comment]
Oh, I am sorry. I was not aware of this and just searched the issues fur duplicates.
I will close this issue since this date should not be a holiday everywhere in bavaria.

Thanks and kind regards
