### ISSUE TITLE
Need new code thats in dev-develop

### ISSUE THREAD

**Issue by WouterVeen** [azuyalabs/yasumi#312]
For the Netherlands I need the addition of the 5 year check for liberation day. So I could use the dev-develop version in composer but the company I work for doesnt allow this. When will there be a release?

**Comment by stelgenhof** [comment]
Thanks for your question. I don't have any target date set, but will try to make a new release as soon as possible.

**Comment by stelgenhof** [comment]
Released version [2.6.0](https://github.com/azuyalabs/yasumi/releases/tag/2.6.0)
