### ISSUE TITLE
[Doc / Help] What should I do if a new holiday is added?

### ISSUE THREAD

**Issue by tokiya-takai** [azuyalabs/yasumi#320]
For example, if I run `composer update azuyalabs/yasumi`, will it reflect the latest information?

**Comment by stelgenhof** [comment]
@tokiya-takai Thank you very much for your question. Running `composer update azuyalabs/yasumi` will update your local installed copy of Yasumi with the latest available version. If a new version of Yasumi contains updates with for example new holidays, then indeed your local version will have those new holidays reflected. 

Hopefully that answers your question. 

Cheers! Sacha

**Comment by tokiya-takai** [comment]
@stelgenhof Thank you for your response! Please let me ask the question again, as it may possibly be misleading.

If there is a change in the holidays due to a change in the law, etc., is the only possible way I can take is to `composer update azuyalabs/yasumi`? If there is another way, please let me know.
Or is there another way I can contribute to Yasumi?

**Comment by stelgenhof** [comment]
@tokiya-takai In case there is a change in holidays, you can either contribute the necessary change yourself by submitting a PR (as described here: https://www.yasumi.dev/docs/contributing/) or raise an issue, which somebody else (i.e. me) will do. 
The standard flow/process is that, after the change is approved, it will be included in a next release and then executing a `composer update azuyalabs/yasumi` will be updated to that new version that includes the changes.

**Comment by tokiya-takai** [comment]
@stelgenhof Thank you very much. Understood.
Thanks to you and the wonderful library Yasumi！
