### ISSUE TITLE
French Holidays of 2024 are not detected :( 

### ISSUE THREAD

**Issue by WalidAxo** [azuyalabs/yasumi#325]
Hello :) 

I'm using your API to subtract holidays from range of dates. It's was working just fine for 2023. Unfortunately, all 2024's French holidays are not detected. Is the API maintained ? 

Thank you for your help, 

Best regards

**Comment by stelgenhof** [comment]
Hi @WalidAxo 

Yes, this library is still maintained :) Yasumi is in essence year independent as holidays are calculated in real-time. 

Can you perhaps share your code how you are trying to get the 2024 holidays? 

Thanks! Sacha

**Comment by WalidAxo** [comment]
Ah perfect, 

excuse me, I think I discovered my mistake :( 

I was creating the object with year 2023 and caculating holidays for 2024. 

You can close this issue. 

Thank you for your time and assistance. 

Best,

**Comment by stelgenhof** [comment]
No problem. Thanks for the reply.
