### ISSUE TITLE
Have you considered using iCalendar

### ISSUE THREAD

**Issue by evert** [azuyalabs/yasumi#33]
This could be useful for a number of projects I'm working on. I'm the author of [sabre/vobject](http://sabre.io/vobject/) and I generally use the mozilla feeds for this:

https://www.mozilla.org/en-US/projects/calendar/holidays/

**Comment by stelgenhof** [comment]
Do you mean using the mozilla feeds instead of this library? Or using the feeds as a source of input for extending Yasumi?

**Comment by evert** [comment]
You could indeed use the source for input, which might make it a bit easier for you to maintain all the data. But my main point was actually the opposite... could you generate iCalendar feeds based on the your source data?

**Comment by stelgenhof** [comment]
That's a nice idea! Definitely possible...

**Comment by stelgenhof** [comment]
Here is an example of all the official Dutch holidays for 2016 (In Dutch), generated using Yasumi:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.0//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:sabre-vobject-e42ea612-2c38-43d6-8dc6-1648e81c12f3
DTSTAMP:20160608T143201Z
SUMMARY:Nieuwjaar
DTSTART:20160101T000000Z
DTEND:20160101T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-17fdf395-d839-4f03-a044-a2ea7e5b1d81
DTSTAMP:20160608T143201Z
SUMMARY:Eerste Paasdag
DTSTART:20160327T000000Z
DTEND:20160327T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-e54280c4-f68d-473c-b9c4-3399812dd406
DTSTAMP:20160608T143201Z
SUMMARY:Tweede Paasdag
DTSTART:20160328T000000Z
DTEND:20160328T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-85ee3bb6-5885-482f-acde-0f9d9139ed15
DTSTAMP:20160608T143201Z
SUMMARY:Koningsdag
DTSTART:20160427T000000Z
DTEND:20160427T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-faf0a8c5-98e4-4580-9e5d-59d8d226306a
DTSTAMP:20160608T143201Z
SUMMARY:Hemelvaart
DTSTART:20160505T000000Z
DTEND:20160505T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-4f8e8f47-ef10-4a34-9dc3-c457dee6ca4a
DTSTAMP:20160608T143201Z
SUMMARY:Eerste Pinksterdag
DTSTART:20160515T000000Z
DTEND:20160515T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-26c41550-8a8f-48c2-b770-c4709f977a1d
DTSTAMP:20160608T143201Z
SUMMARY:Tweede Pinksterdag
DTSTART:20160516T000000Z
DTEND:20160516T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-793304e8-cbab-489b-9a54-79441e6e3e46
DTSTAMP:20160608T143201Z
SUMMARY:Kerstmis
DTSTART:20161225T000000Z
DTEND:20161225T000000Z
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-83f8ae2d-6c56-45f2-92c7-6d5d5a28e1a3
DTSTAMP:20160608T143201Z
SUMMARY:Tweede Kerstdag
DTSTART:20161226T000000Z
DTEND:20161226T000000Z
END:VEVENT
END:VCALENDAR
```

**Comment by evert** [comment]
That's a nice start! A few suggestions:

1. Make sure these are marked as all-day events. In practice this means you can drop `DTEND` and specify `DTSTART`:

    DTSTART;VALUE=DATE:20160505

Another thing that would be really great is to actually encode the rules in the events. Christmas is easy, because it's on the same date very year:

    RRULE:FREQ=YEARLY

Easter and related holidays very hard to express with `RRULE` though :( I don't even know for sure if it's possible. But for those you could also use something like `RDATE` to express easter dates that will happen in the future. This encodes the next 3 years for easter:

    RDATE;VALUE=DATE:20170416,20180418,20190421

**Comment by stelgenhof** [comment]
Here is the quick example with all holidays set as all-day events:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.0//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:sabre-vobject-390c38f2-7b50-4c14-b87c-de4264c68756
DTSTAMP:20160608T213452Z
SUMMARY:Nieuwjaar
DTSTART:VALUE=DATE:20160101
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-4908fffe-2b65-40bd-a0fc-e2b7885bda19
DTSTAMP:20160608T213452Z
SUMMARY:Eerste Paasdag
DTSTART:VALUE=DATE:20160327
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-ac14d34c-fb7d-44ac-8480-826d597eca17
DTSTAMP:20160608T213452Z
SUMMARY:Tweede Paasdag
DTSTART:VALUE=DATE:20160328
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-eb04e5c1-7071-461f-b86a-5622c5949f1c
DTSTAMP:20160608T213452Z
SUMMARY:Koningsdag
DTSTART:VALUE=DATE:20160427
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-c5ebd4b9-ba7c-4d87-85f8-127ad94282f5
DTSTAMP:20160608T213452Z
SUMMARY:Hemelvaart
DTSTART:VALUE=DATE:20160505
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-32d0961d-f54d-40ee-baa2-4d174e84c94c
DTSTAMP:20160608T213452Z
SUMMARY:Eerste Pinksterdag
DTSTART:VALUE=DATE:20160515
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-3429afc8-9497-4a56-a44b-ff6881843e3b
DTSTAMP:20160608T213452Z
SUMMARY:Tweede Pinksterdag
DTSTART:VALUE=DATE:20160516
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-51eacc08-7bea-4bb7-b78e-fb9f248282e5
DTSTAMP:20160608T213452Z
SUMMARY:Kerstmis
DTSTART:VALUE=DATE:20161225
END:VEVENT
BEGIN:VEVENT
UID:sabre-vobject-afeb6f62-b76c-4ac9-ad94-5c9b6d79180a
DTSTAMP:20160608T213452Z
SUMMARY:Tweede Kerstdag
DTSTART:VALUE=DATE:20161226
END:VEVENT
END:VCALENDAR
```

As for the rules, yes it depends on the holiday and in Yasumi I don't specify any rule specifically. That would make it a bit more challenging to implement, but possible. 
For irregular holidays, RRULE can work. I am just wondering if we have a large year range if a large list of dates is possible. (Sorry haven't checked the VCALENDAR specs fully yet).

**Comment by brucealdridge** [comment]
I think this would be a good point of call for testing. Both for current data and alerting to new changed holiday dates in future.

Australia\Victoria - http://www.vic.gov.au/themes/v6/images/VictoriaCalendar-PublicHolidays.ics
NewZealand - https://www.employment.govt.nz/leave-and-holidays/public-holidays/public-holidays-and-anniversary-dates/icalendar-feeds/

I'm sure other countries/regions have these also

**Comment by stelgenhof** [comment]
The main goal of this library is to provide the national holidays of various countries. An export feature was not on my mind when I started this. However it could be added in the future. 

Perhaps if we add the example I made as part of the documentation / examples, people can see how the library can be used.
