### ISSUE TITLE
Holiday calculation functions in providers are private, could those be protected instead?

### ISSUE THREAD

**Issue by attepulkkinen** [azuyalabs/yasumi#331]
I think the holiday calculation functions in the provider classes should be protected instead of private (as discussed here #276), this would make it much easier to extend the current providers as I don't have to copy-paste functions from the parent class to use them in extending class. For example:

https://github.com/azuyalabs/yasumi/blob/59e2bf6f8e90ff86817b98003b63251e0e9b07bb/src/Yasumi/Provider/Finland.php#L153
https://github.com/azuyalabs/yasumi/blob/59e2bf6f8e90ff86817b98003b63251e0e9b07bb/src/Yasumi/Provider/Greece.php#L114
https://github.com/azuyalabs/yasumi/blob/59e2bf6f8e90ff86817b98003b63251e0e9b07bb/src/Yasumi/Provider/Luxembourg.php#L109

I can provide pull-request if needed

**Comment by stelgenhof** [comment]
Hi @attepulkkinen Thank you very much for raising this. Indeed as per the #276 discussion, these methods can be changed to `protected`. I haven't actively changed this for all the providers (yet). 

I would indeed appreciate if you could create a PR for this.
