### ISSUE TITLE
Request to Add Assumption Day for Bavaria in Yasumi

### ISSUE THREAD

**Issue by Hatemnaser** [azuyalabs/yasumi#339]
Hello Yasumi Team,

I'm using Yasumi to manage public holidays in Germany but noticed that Assumption Day (August 15th), which is a public holiday in Bavaria, is missing from the library. Could you please consider adding this holiday to the Bavaria provider? This addition would help accurately reflect local holidays for users managing schedules in this region.

For reference on the holiday, please see: [Assumption Day in Bavaria](https://publicholidays.de/assumption-day/)

Thank you for considering this request.

Best regards,

**Comment by Hatemnaser** [comment]
Hello Yasumi Team,

I wanted to follow up on my previous request regarding adding Assumption Day (August 15th) as a public holiday for Bavaria in the Yasumi library. Is there any update on whether this will be implemented?

Thank you for your attention to this matter.

Best regards,

**Comment by stelgenhof** [comment]
@Hatemnaser Apologies for the late reply as I have been traveling for business. Let me check this week.

**Comment by stelgenhof** [comment]
@Hatemnaser I've added the Assumption of Mary to Bavaria. It is available in the `dev` branch and targeted for the 2.8.0 release (not date determined yet).

**Comment by Hatemnaser** [comment]
Thank you very much for the update, look forward to the 2.8.0 release.

**Comment by Hatemnaser** [comment]
Hello @stelgenhof, do you have an estimate on when the 2.8.0 release might be available?
