### ISSUE TITLE
China

### ISSUE THREAD

**Issue by splitice** [azuyalabs/yasumi#42]
Probably the most populous missing country. And one of the most disruptive public holidays for shipping (Chinese New Years)

I personally have no need for it at this stage, just thought it perhaps belongs on the TODO list.

**Comment by stelgenhof** [comment]
Yes, I know. I was working on the holidays for Taiwan (similar to the Chinese ones). The library is based on arithmetic calendars. However some countries/cultures apply calendars that are not arithmetic. There do have some kind of algorithm but very complex. 

So definitely something I'd like to have but will take a while before figuring that one out. I'll add it to the TODO list :)

**Comment by AGDholo** [comment]
Some holiday dates in China will change slightly with the date of the weekend, and someone may need to manually maintain it at regular intervals.
