### ISSUE TITLE
Incorrect All Saints' Day in Finland provider

### ISSUE THREAD

**Issue by tplantta** [azuyalabs/yasumi#43]
Correct date is Saturday between 31 Oct and 6 Nov, since 1955 or 1956, the two references below seem to disagree about the exact year. Before that 1st Sunday of November since 1774.

http://www.timeanddate.com/holidays/finland/all-saints
https://fi.wikipedia.org/wiki/Pyh%C3%A4inp%C3%A4iv%C3%A4

**Comment by stelgenhof** [comment]
Thanks for letting me know. I'll have a look at this. 

Cheers! Sacha

**Comment by tplantta** [comment]
Yes, it is not 1st of November in Finland. The English wikipedia article you linked doesn't explicitly mention Finland in that context, but what is said about most Lutheran churches in general is more or less true in Finland. Currently correct date is Saturday between 31st Oct and 6th Nov, same as in Sweden. Earlier it was on 1st Sunday of November. The two references I linked in the initial report disagree about the exact year for that change, and for now I have no further information to tell which of them is inaccurate. The Finnish wikipedia arcticle also implies it was on 1st Sunday of November in Sweden too in the past, which isn't taken into account in Sweden provider. That is a different issue though, and not nearly as urgent as it only affects historical dates several decades in the past.

From Wikipedia:
"The festival was retained after the Reformation in the calendar of the Anglican Church and in many Lutheran churches.[21] In the Lutheran churches, such as the Church of Sweden, it assumes a role of general commemoration of the dead. In the Swedish calendar, the observance takes place on the Saturday between 31 October and 6 November. In many Lutheran Churches, it is moved to the first Sunday of November"

**Comment by stelgenhof** [comment]
Thanks! I wasn't aware of that; having learned something new again :). I believe we can then correct this by implementing in the same manner as done for Sweden.

**Comment by stelgenhof** [comment]
@tplantta I have resolved the issue. You can pull the dev branch to check if it is working now :)

**Comment by stelgenhof** [comment]
Assuming it is working now :) If not, please create a new issue or reopen this one.
