### ISSUE TITLE
Consider the use of "instanceof" instead of "get_class"

### ISSUE THREAD

**Issue by samag** [azuyalabs/yasumi#49]
Looking at

    // If given date is a DateTime object; check if it falls in the weekend
    if (get_class($date) === 'DateTime') {
        if (in_array($date->format('w'), $this->weekend_days)) {
            return false;
        }
    }

the condition fails for any subclasses of `DateTime` (like the very popular **Carbon** class) which needlessly limits your APIs scope. Please consider the `instanceof` operator to allow for classes that derive from `DateTime`.

**Comment by stelgenhof** [comment]
It does seem indeed a better way to verify the class with the `instanceof` operator. Thanks for the suggestion!

**Comment by stelgenhof** [comment]
Resolved.
