### ISSUE TITLE
Provider for Israel

### ISSUE THREAD

**Issue by AronNovak** [azuyalabs/yasumi#58]
Potentially based on https://github.com/mooffie/holidays
See also:
https://en.wikipedia.org/wiki/Public_holidays_in_Israel

**Comment by AronNovak** [comment]
As implementing the logic for this provider would totally differ from all we have, due to a totally separate date system in use, would it be acceptable to ember https://github.com/mooffie/holidays via composer, where this problem is already solved?

**Comment by stelgenhof** [comment]
Thanks for creating this issue. I am not familiar with the Jewish Calendar system, however Yasumi's base calendar system is Gregorian. From what I can see, it should be possible to map the Jewish holidays to the Gregorian system. 

No sure what you mean by 'embed', but that library seems quite old. I prefer not to have any dependencies in this library as the goal is that Yasumi provides all the calculations/algorithms itself.
