### ISSUE TITLE
add yasumi creation by ISO3166-2 code

### ISSUE THREAD

**Issue by huehnerhose** [azuyalabs/yasumi#61]
I want to get holidays based on dynamically gathered region informations. The ISO3166-2 codes I can get out of various map-api. 
As far as I can see the `const ID` inside the providers corresponce to ISO3166-2 and is used as index for the `getProviders()` return array. 

Therefore I made a simple [wrapper](https://github.com/InSitu-Software/yasumi/commit/472aba9c7c958ab1bccd0083a5fba4133be1e813). There aren't any test for this wrapper implemented and I only "tested" it against my usage. (Germany and Subdivisions of Germany).

So this is kind of a "Feature Request" / "Pull Request" mix :)

**Comment by stelgenhof** [comment]
Very nice! Some others have asked a similar feature as currently you need to know the exact name of the Holiday provider. Would you be able to create a PR?

**Comment by stelgenhof** [comment]
Closing issue. Resolved by PR #62
