### ISSUE TITLE
Bank holidays in United Kingdom

### ISSUE THREAD

**Issue by serverfire** [azuyalabs/yasumi#64]
Your package return this holidays for united kingdom:
array:7 [▼
  "newYearsDay" => "2017-01-02"
  "goodFriday" => "2017-04-14"
  "easterMonday" => "2017-04-17"
  "mayDayBankHoliday" => "2017-05-01"
  "springBankHoliday" => "2017-05-29"
  "christmasDay" => "2017-12-25"
  "secondChristmasDay" => "2017-12-26"
]
but refer to https://www.gov.uk/bank-holidays holidays must be 8 days for 2017!

**Comment by stelgenhof** [comment]
Thanks for catching this. Indeed it seems that the Summer Bank Holiday is missing.

**Comment by stelgenhof** [comment]
@serverfire Added the missing Summer Bank Holiday. Would you mind checking again using the latest commit? Thanks!
