### ISSUE TITLE
Wrong translation for Eastern in Austria

### ISSUE THREAD

**Issue by juergenweb** [azuyalabs/yasumi#66]
Hello,
on line 18 of  yasumi/src/Yasumi/data/translations/easter.php the translation for Eastern in the Austrian language is:

```
'de_AT' => 'Oster',

```
but the correct translation in the Austrian language has to be

```
'de_AT' => 'Ostersonntag',

```

In Austria we call it "Easter sunday" (=Ostersonntag).

Best regards Jürgen

**Comment by stelgenhof** [comment]
Thank you for the correction. Let me alter this as soon as possible.

**Comment by stelgenhof** [comment]
Changed.
