### ISSUE TITLE
United Kingdom doesn't return the summer bank holiday

### ISSUE THREAD

**Issue by LNCH** [azuyalabs/yasumi#79]
I'm looking into integrating this package with our businesses annual leave calendar, however for the UK it's missing the summer bank holiday 

In the UK this holiday falls on the last Monday of August, and in Scotland it falls on the first Monday of the month

**Comment by LNCH** [comment]
After forking the repo I can see that the master branch has the summer bank holiday included in the UK's holidays, however it's not included in the most recent packagist release. So when I install the package through composer, I'm mising the summer bank holidays

**Comment by stelgenhof** [comment]
Yes, that's normal :) I haven't yet officially released recent changes, fixes, etc. in a new release. You are more than welcome to use the master branch in your project. In your Composer file, you can specify to use the master branch in stead of the latest official release.

**Comment by stelgenhof** [comment]
Closing this issue as it has been addressed already in the master branch and will be included in the upcoming v1.7.0 release.
