### ISSUE TITLE
Spain: Easter sunday not an official holiday?

### ISSUE THREAD

**Issue by bkonetzny** [azuyalabs/yasumi#83]
Yasumi lists 01.04.2018 (Easter Sunday) for Spain as an official holiday. I checked several sources and can't find any reference to this.

Sources I checked:
* https://www.timeanddate.com/calendar/?year=2018&country=16
* https://publicholidays.es/2018-dates/
* http://www.noworkdays.com/spain/2018

Good friday is a national holiday and easter monday is listed as a regional holiday, which is identical to listing in Yasumi dataset.
I think (Easter Sunday) should be removed from Spain holidays?

**Comment by lukosius** [comment]
Good catch. I think the holiday should be changed to the observance type.

https://es.wikipedia.org/wiki/Calendario_laboral

**Comment by stelgenhof** [comment]
My assumption here was that if Easter Monday is celebrated, then Easter Sunday must be celebrated as well (as it happens as so in other countries). Likely my assumption was wrong then :)

I checked also this resource: https://www.boe.es/boe/dias/2017/10/11/pdfs/BOE-A-2017-11639.pdf
and Easter Sunday isn't mentioned anywhere. So it does seem to be that it isn't a holiday at all.

**Comment by lukosius** [comment]
I thought we can leave it as an observance type because because it ends the holy week in Spain, but I'm not sure.

https://en.wikipedia.org/wiki/Holy_Week_procession

**Comment by stelgenhof** [comment]
According to that source, it should be an observance in selected regions only.

**Comment by bkonetzny** [comment]
@stelgenhof Which source of the links above are you referring to? If thats an spanish source, can you point me to a english variant so I can fix the PR?

**Comment by stelgenhof** [comment]
@bkonetzny I was referring to the PDF in my above comment. However, after reading it a bit more thoroughly, my assumption that it was only observed in selected regions was wrong. Easter Sunday is not an 'official' holiday as such in all of Spain and setting this a 'observance' makes sense (also it falls on a Sunday anyway). 

Don't need to fix your PR. I'll have another look and merge it (if it is fine).
