### ISSUE TITLE
Support for Islamic Calendar

### ISSUE THREAD

**Issue by TheAdnan** [azuyalabs/yasumi#93]
Have you thought about adding a Trait for the Islamic Holidays?

**Comment by stelgenhof** [comment]
@TheAdnan Definitely thought about but not yet investigated. I'm not familiar with Islamic holidays how these could be added in a calculated way. Do you maybe have an idea or a good resource?

Cheers! Sacha

**Comment by TheAdnan** [comment]
I did a bit of research, and I found these implementation for the Islamic (Hijri) calendar:

- [https://www.phpclasses.org/package/9435-PHP-Convert-and-manipulate-Hijri-dates.html](url)

- [http://php.net/manual/en/ref.calendar.php#54234](url)

**Comment by stelgenhof** [comment]
Thanks! These are great resources. I'll have a look into that. I need to understand more about the Islamic calendars first :)
